version: 2
jobs:
  build:
    working_directory: ~/hslu_maven_demo
    docker:
      - image: maven:3.5.0-jdk-8
    steps:
      - checkout
      - run: mvn dependency:go-offline -B
      - run: mvn test -B
